server:
  port: 8080
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3308
  database: cabbage
  username: root
  password: root123456
  charset: utf8mb4
  loc: Asia/Shanghai
  tableprefix: cabbage_
errors:
  userNotFound:
    message: user not found
    code: 1001